<?php
$labels = array();
$labels['gravatar_plugin'] = 'Contactes Gravatar';
$labels['gravatar_use'] = 'Utilitzar Gravatar';
$labels['gravatar_size'] = 'Mida del avatar (px)';
$labels['gravatar_rating'] = 'Puntuació del avatar';
$labels['gravatar_G'] = 'G';
$labels['gravatar_PG'] = 'PG';
$labels['gravatar_R'] = 'R';
$labels['gravatar_X'] = 'X';
$labels['gravatar_use_custom'] = 'Utilitzar API definida (sempre te preferencia)';
