<?php
//Translation by Malte Kiefer (@beli3ver)
$labels = array();
$labels['gravatar_plugin'] = 'Gravatar Adressbuch';
$labels['gravatar_use'] = 'Gravatar nutzen';
$labels['gravatar_size'] = 'Avatar Größe (px)';
$labels['gravatar_rating'] = 'Avatar Einstufung';
$labels['gravatar_G'] = 'G Einstufung';
$labels['gravatar_PG'] = 'PG Einstufung';
$labels['gravatar_R'] = 'R Einstufung';
$labels['gravatar_X'] = 'X Einstufung';
$labels['gravatar_use_custom'] = 'Benutze definiert API (Es hat immer Vorrang)';
