<?php
$labels = array();
$labels['gravatar_plugin'] = 'Gravatar Address Book';
$labels['gravatar_use'] = 'Use Gravatar';
$labels['gravatar_size'] = 'Avatar size (px)';
$labels['gravatar_rating'] = 'Avatar rating';
$labels['gravatar_G'] = 'G rated';
$labels['gravatar_PG'] = 'PG rated';
$labels['gravatar_R'] = 'R rated';
$labels['gravatar_X'] = 'X rated';
$labels['gravatar_use_custom'] = 'Use defined API (it always has preference)';
