<?php
$labels = array();
$labels['gravatar_plugin'] = 'Contactos Gravatar';
$labels['gravatar_use'] = 'Usar Gravatar';
$labels['gravatar_size'] = 'Tamaño del avatar (px)';
$labels['gravatar_rating'] = 'Puntuación del avatar';
$labels['gravatar_G'] = 'G';
$labels['gravatar_PG'] = 'PG';
$labels['gravatar_R'] = 'R';
$labels['gravatar_X'] = 'X';
$labels['gravatar_use_custom'] = 'Usar API definida (siempre tiene preferencia)';
