<?php
//Translation by Jérôme Dubois
$labels = array();
$labels['gravatar_plugin'] = 'Carnet d\'adresses Gravatar';
$labels['gravatar_use'] = 'Utiliser Gravatar';
$labels['gravatar_size'] = 'Taille des avatars (en pixels)';
$labels['gravatar_rating'] = 'Classement des avatars';
$labels['gravatar_G'] = 'Tout public (G)';
$labels['gravatar_PG'] = 'Public accompagné (PG)';
$labels['gravatar_R'] = 'Public restreint (R)';
$labels['gravatar_X'] = 'Public adulte (X)';
$labels['gravatar_use_custom'] = 'Utiliser l\'API définie (toujours prioritaire)';
