<?php
$labels = array();
$labels['gravatar_plugin'] = 'Awatary Adresowe Gravatar';
$labels['gravatar_use'] = 'Używaj Zdjęć z Gravatar';
$labels['gravatar_size'] = 'Rozmiar Awatara (px)';
$labels['gravatar_rating'] = 'Wyświetlanie wg. Oceny Dojrzałości Awatarów';
$labels['gravatar_G'] = 'G (dla dzieci i dorosłych)';
$labels['gravatar_PG'] = 'PG (pod nadzorem dorosłych)';
$labels['gravatar_R'] = 'R (może zawierać treści nieodpowiednie dla dzieci)';
$labels['gravatar_X'] = 'X (nie dla dzieci)';
$labels['gravatar_use_custom'] = 'Użyj zdefiniowanego API (zawsze ma pierwszeństwo)';
